function [out, chPathG] = channel( in, sim_params )
%% 参数表
chanRate = sim_params.chanSRate;  %采样率
fc = 5.9e9;         %载频
lightSpeed = 299792458;
% EVA_delay = [0,30,150,310,370,710,1090,1730,2510]*1e-9;      %信道延迟
% EVA_gain = [0,-1.5,-1.4,-3.6,-0.6,-9.1,-7,-12,-16.9];   %信道增益
EVA_delay = [0 1 3 4 7 10]*(1/chanRate);
EVA_gain  = [0 -1 -9 -10 -15 -20];
user_speed = sim_params.user_speed;   %用户移动速度
maxDopplerShift = user_speed/lightSpeed*fc;
%% 衰落信道
% persistent chanObj;
% if isempty(chanObj)
    switch sim_params.chanMode
        case 'rayleigh'
            chanObj = comm.RayleighChannel(...
                'SampleRate',chanRate, ...
                'PathDelays',EVA_delay, ...
                'AveragePathGains',EVA_gain, ...
                'NormalizePathGains',true, ...          
                'PathGainsOutputPort', true,... %Enable path gain output (logical)
                'MaximumDopplerShift',maxDopplerShift); 
        case 'MIMO'
            chanObj = comm.MIMOChannel('SampleRate', chanRate, ...
                    'MaximumDopplerShift', maxDopplerShift, ...
                    'PathDelays', EVA_delay,...
                    'AveragePathGains', EVA_gain,...
                    'SpatialCorrelation', false ,...
                    'NumTransmitAntennas', 1,...     
                    'NumReceiveAntennas', sim_params.Rx,...            
                    'PathGainsOutputPort', true,...
                    'NormalizePathGains', true,...
                    'NormalizeChannelOutputs', true);      
        case 'LTEMIMO'
            chanObj = comm.LTEMIMOChannel(...
              'Profile',              'EVA 70Hz',...
              'AntennaConfiguration', '1x2',...
              'CorrelationLevel',     'Low',...
              'AntennaSelection',     'Off',...
              'PathGainsOutputPort',  true);  
    end
% end
        [out, chPathG] = step(chanObj, in);    
end

